name: solarrad
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - python-dateutil
  - numpy
  - pandas
  - mysql-connector-python
  - scikit-learn
  - scipy
  - sqlite
  - texttable

